---

apiVersion: apiextensions.k8s.io/v1

kind: CustomResourceDefinition

metadata:

  name: cockroachdbs.charts.example.com

spec:

  group: charts.example.com

  names:

    kind: Cockroachdb

    listKind: CockroachdbList

    plural: cockroachdbs

    singular: cockroachdb

  scope: Namespaced

  versions:

  - name: v1alpha1

    schema:

      openAPIV3Schema:

        description: Cockroachdb is the Schema for the cockroachdbs API

        properties:

          apiVersion:

            description: 'APIVersion defines the versioned schema of this representation

              of an object. Servers should convert recognized schemas to the latest

              internal value, and may reject unrecognized values. More info: https://git.k$

            type: string

          kind:

            description: 'Kind is a string value representing the REST resource this

              object represents. Servers may infer this from the endpoint the client

              submits requests to. Cannot be updated. In CamelCase. More info: https://git$

            type: string

          metadata:

            type: object

          spec:

            description: Spec defines the desired state of Cockroachdb

            type: object

            x-kubernetes-preserve-unknown-fields: true

          status:

            description: Status defines the observed state of Cockroachdb

            type: object

            x-kubernetes-preserve-unknown-fields: true

        type: object

    served: true

    storage: true
